[package]
name = "kora-lib-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
arbitrary = { workspace = true, features = ["derive"] }
async-trait = { workspace = true }
libfuzzer-sys = "0.4"
pollster = "0.4.0"
serde_json = { workspace = true }
solana-client = { workspace = true }
solana-message = { workspace = true }
solana-sdk = { workspace = true }
solana-system-interface = { workspace = true }
solana-transaction-status-client-types = { workspace = true }
spl-token-2022-interface = { workspace = true }
spl-token-interface = { workspace = true }
litesvm = "0.8.1"
litesvm-token = "0.8.1"
base64 = { workspace = true }
solana-account-decoder = "3.0.8"

[dependencies.kora-lib]
path = ".."
features = ["fuzzing"]

[[bin]]
name = "fuzz_target_1"
path = "fuzz_targets/fuzz_target_1.rs"
test = false
doc = false
bench = false
